- pt_BR/appendices/about.xml
Fiz apenas uma pequena no contexto "Há três maneiras de ajudar a melhoras a documentação." para "Há três maneiras de ajudar a melhorar a documentação." e "Como ajudar a melhoras a documentação" para "Como ajudar a melhorar a documentação". No caso, para poder fazer o salvamento tive que mudar a permissão do arquivo "about.xml", não sei se isso seria um procedimento correto.
> Correção de algumas palavras e concordância

- pt_BR/reference/intl/intlcodepointbreakiterator/getlastcodepoint.xml
Esse pull request sobrescreve o erro cometido no #4
> Tradução de reference/intl/intlcodepointbreakiterator/*

- pt_BR/reference/intl/intlpartsiterator/getbreakiterator.xml
Esse pull request sobrescreve o erro cometido no #4
> Tradução de reference/intl/intlpartsiterator/*

- pt_BR/reference/intl/resourcebundle/count.xml
- pt_BR/reference/intl/resourcebundle/create.xml
- pt_BR/reference/intl/resourcebundle/get-error-code.xml
- pt_BR/reference/intl/resourcebundle/get-error-message.xml
- pt_BR/reference/intl/resourcebundle/get.xml
- pt_BR/reference/intl/resourcebundle/locales.xml
Esse pull request sobrescreve o erro cometido no #4
> Tradução de reference/intl/resourcebundle/*

- pt_BR/reference/intl/uconverter/construct.xml
- pt_BR/reference/intl/uconverter/convert.xml
- pt_BR/reference/intl/uconverter/fromucallback.xml
- pt_BR/reference/intl/uconverter/getaliases.xml
- pt_BR/reference/intl/uconverter/getavailable.xml
- pt_BR/reference/intl/uconverter/getdestinationencoding.xml
- pt_BR/reference/intl/uconverter/getdestinationtype.xml
- pt_BR/reference/intl/uconverter/geterrorcode.xml
- pt_BR/reference/intl/uconverter/geterrormessage.xml
- pt_BR/reference/intl/uconverter/getsourceencoding.xml
- pt_BR/reference/intl/uconverter/getsourcetype.xml
- pt_BR/reference/intl/uconverter/getstandards.xml
- pt_BR/reference/intl/uconverter/getsubstchars.xml
- pt_BR/reference/intl/uconverter/reasontext.xml
- pt_BR/reference/intl/uconverter/setdestinationencoding.xml
- pt_BR/reference/intl/uconverter/setsourceencoding.xml
- pt_BR/reference/intl/uconverter/setsubstchars.xml
- pt_BR/reference/intl/uconverter/toucallback.xml
- pt_BR/reference/intl/uconverter/transcode.xml
Esse pull request sobrescreve o erro cometido no #4
> Tradução de reference/intl/uconverter/*

- pt_BR/reference/zmq/zmq/construct.xml
> Tradução de reference/zmq/zmq/*

- pt_BR/reference/zmq/zmqcontext/construct.xml
- pt_BR/reference/zmq/zmqcontext/getopt.xml
- pt_BR/reference/zmq/zmqcontext/getsocket.xml
- pt_BR/reference/zmq/zmqcontext/ispersistent.xml
- pt_BR/reference/zmq/zmqcontext/setopt.xml
> Tradução de reference/zmq/zmqcontext/*

- pt_BR/reference/zmq/zmqdevice/construct.xml
- pt_BR/reference/zmq/zmqdevice/getidletimeout.xml
- pt_BR/reference/zmq/zmqdevice/gettimertimeout.xml
- pt_BR/reference/zmq/zmqdevice/run.xml
- pt_BR/reference/zmq/zmqdevice/setidlecallback.xml
- pt_BR/reference/zmq/zmqdevice/setidletimeout.xml
- pt_BR/reference/zmq/zmqdevice/settimercallback.xml
- pt_BR/reference/zmq/zmqdevice/settimertimeout.xml
> Tradução de reference/zmq/zmqdevice/*

- pt_BR/reference/zmq/zmqpoll/add.xml
- pt_BR/reference/zmq/zmqpoll/clear.xml
- pt_BR/reference/zmq/zmqpoll/count.xml
- pt_BR/reference/zmq/zmqpoll/getlasterrors.xml
- pt_BR/reference/zmq/zmqpoll/poll.xml
- pt_BR/reference/zmq/zmqpoll/remove.xml
> Tradução de reference/zmq/zmqpoll/*

- pt_BR/reference/zmq/zmqsocket/bind.xml
- pt_BR/reference/zmq/zmqsocket/connect.xml
- pt_BR/reference/zmq/zmqsocket/construct.xml
- pt_BR/reference/zmq/zmqsocket/disconnect.xml
- pt_BR/reference/zmq/zmqsocket/getendpoints.xml
- pt_BR/reference/zmq/zmqsocket/getpersistentid.xml
- pt_BR/reference/zmq/zmqsocket/getsockettype.xml
- pt_BR/reference/zmq/zmqsocket/getsockopt.xml
- pt_BR/reference/zmq/zmqsocket/ispersistent.xml
- pt_BR/reference/zmq/zmqsocket/recv.xml
- pt_BR/reference/zmq/zmqsocket/recvmulti.xml
- pt_BR/reference/zmq/zmqsocket/send.xml
- pt_BR/reference/zmq/zmqsocket/sendmulti.xml
- pt_BR/reference/zmq/zmqsocket/setsockopt.xml
- pt_BR/reference/zmq/zmqsocket/unbind.xml
> Tradução de reference/zmq/zmqsocket/*

- pt_BR/reference/lua/lua/assign.xml
- pt_BR/reference/lua/lua/call.xml
- pt_BR/reference/lua/lua/construct.xml
- pt_BR/reference/lua/lua/eval.xml
- pt_BR/reference/lua/lua/getversion.xml
- pt_BR/reference/lua/lua/include.xml
- pt_BR/reference/lua/lua/registercallback.xml
Tradução da API da extensão LUA para PHP [ Ref #15 ]
> Tradução de reference/lua/lua/*

- pt_BR/reference/lua/luaclosure/invoke.xml
Tradução da API da extensão LUA para PHP [ Ref #15 ]
> Tradução de reference/lua/luaclosure/*

- pt_BR/reference/session/sessionhandler/close.xml
- pt_BR/reference/session/sessionhandler/create-sid.xml
- pt_BR/reference/session/sessionhandler/destroy.xml
- pt_BR/reference/session/sessionhandler/gc.xml
- pt_BR/reference/session/sessionhandler/open.xml
- pt_BR/reference/session/sessionhandler/read.xml
- pt_BR/reference/session/sessionhandler/write.xml
Tradução, até então inexistente, dos arquivos reference/session/sessionhandler/*.xml
> Novas traduções de reference/session/sessionhandler/*.xml

- pt_BR/reference/session/sessionhandlerinterface/close.xml
- pt_BR/reference/session/sessionhandlerinterface/destroy.xml
- pt_BR/reference/session/sessionhandlerinterface/gc.xml
- pt_BR/reference/session/sessionhandlerinterface/open.xml
- pt_BR/reference/session/sessionhandlerinterface/read.xml
- pt_BR/reference/session/sessionhandlerinterface/write.xml
Tradução, até então inexistente, dos arquivos reference/session/sessionhandlerinterface/*.xml
> Novas traduções de reference/session/sessionhandlerinterface/*.xml

- pt_BR/reference/filesystem/functions/basename.xml
- pt_BR/reference/filesystem/functions/disk-free-space.xml
- pt_BR/reference/filesystem/functions/disk-total-space.xml
- pt_BR/reference/filesystem/functions/fgetcsv.xml
- pt_BR/reference/filesystem/functions/file-exists.xml
- pt_BR/reference/filesystem/functions/filesize.xml
- pt_BR/reference/filesystem/functions/fputcsv.xml
- pt_BR/reference/filesystem/functions/is-executable.xml
- pt_BR/reference/filesystem/functions/is-file.xml
- pt_BR/reference/filesystem/functions/popen.xml
- pt_BR/reference/filesystem/functions/tmpfile.xml
- pt_BR/reference/filesystem/functions/umask.xml
Atualização dos arquivos que estavam desatualizados de reference/filesystem/functions/*.xml
> Atualização das traduções de reference/filesystem/functions/*.xml

- pt_BR/reference/filesystem/book.xml
- pt_BR/reference/filesystem/setup.xml
Atualização das traduções desatualizadas de reference/filesystem/*.xml
> Atualização das traduções de reference/filesystem/*.xml

- pt_BR/reference/mysql/examples.xml
- pt_BR/reference/mysql/functions/mysql-affected-rows.xml
- pt_BR/reference/mysql/functions/mysql-close.xml
- pt_BR/reference/mysql/functions/mysql-create-db.xml
- pt_BR/reference/mysql/functions/mysql-data-seek.xml
- pt_BR/reference/mysql/functions/mysql-db-name.xml
- pt_BR/reference/mysql/functions/mysql-drop-db.xml
- pt_BR/reference/mysql/functions/mysql-errno.xml
- pt_BR/reference/mysql/functions/mysql-fetch-assoc.xml
- pt_BR/reference/mysql/functions/mysql-fetch-lengths.xml
- pt_BR/reference/mysql/functions/mysql-fetch-object.xml
- pt_BR/reference/mysql/functions/mysql-fetch-row.xml
- pt_BR/reference/mysql/functions/mysql-field-len.xml
- pt_BR/reference/mysql/functions/mysql-field-name.xml
- pt_BR/reference/mysql/functions/mysql-field-seek.xml
- pt_BR/reference/mysql/functions/mysql-field-table.xml
- pt_BR/reference/mysql/functions/mysql-field-type.xml
- pt_BR/reference/mysql/functions/mysql-get-client-info.xml
- pt_BR/reference/mysql/functions/mysql-get-host-info.xml
- pt_BR/reference/mysql/functions/mysql-get-proto-info.xml
- pt_BR/reference/mysql/functions/mysql-get-server-info.xml
- pt_BR/reference/mysql/functions/mysql-info.xml
- pt_BR/reference/mysql/functions/mysql-insert-id.xml
- pt_BR/reference/mysql/functions/mysql-list-dbs.xml
- pt_BR/reference/mysql/functions/mysql-list-fields.xml
- pt_BR/reference/mysql/functions/mysql-list-processes.xml
- pt_BR/reference/mysql/functions/mysql-num-fields.xml
- pt_BR/reference/mysql/functions/mysql-num-rows.xml
- pt_BR/reference/mysql/functions/mysql-ping.xml
- pt_BR/reference/mysql/setup.xml
Atualização das traduções desatualizadas de reference/mysql
> Atualização das traduções desatualizadas de reference/mysql

- pt_BR/reference/session/functions/session-destroy.xml
- pt_BR/reference/session/functions/session-regenerate-id.xml
- pt_BR/reference/session/functions/session-set-save-handler.xml
- pt_BR/reference/session/security.xml
- pt_BR/reference/session/sessionhandlerinterface/gc.xml
- pt_BR/reference/session/sessionhandlerinterface/open.xml
Atualização das traduções desatualizadas de reference/session
> Atualização das traduções de reference/session

- pt_BR/reference/pdo/ini.xml
Atualização dos arquivos desatualizados de reference/pdo
> Atualização das traduções de reference/pdo

- pt_BR/reference/pdo_mysql/constants.xml
- pt_BR/reference/pdo_mysql/reference.xml
Atualização dos arquivos desatualizados de reference/pdo_mysql
> Atualização dos arquivos desatualizados de reference/pdo_mysql

- pt_BR/reference/curl/book.xml
- pt_BR/reference/curl/configure.xml
- pt_BR/reference/curl/constants.xml
- pt_BR/reference/curl/functions/curl-errno.xml
- pt_BR/reference/curl/setup.xml
Atualização dos arquivos desatualizados de reference/curl
> Atualização dos arquivos desatualizados de reference/curl

- pt_BR/reference/curl/curlfile.xml
- pt_BR/reference/curl/functions/curl-escape.xml
- pt_BR/reference/curl/functions/curl-file-create.xml
- pt_BR/reference/curl/functions/curl-multi-setopt.xml
- pt_BR/reference/curl/functions/curl-multi-strerror.xml
- pt_BR/reference/curl/functions/curl-pause.xml
- pt_BR/reference/curl/functions/curl-reset.xml
- pt_BR/reference/curl/functions/curl-share-close.xml
- pt_BR/reference/curl/functions/curl-share-init.xml
- pt_BR/reference/curl/functions/curl-share-setopt.xml
- pt_BR/reference/curl/functions/curl-strerror.xml
- pt_BR/reference/curl/functions/curl-unescape.xml
Novas traduções de reference/curl
> Novas traduções de reference/curl

- pt_BR/features/commandline.xml
Fixed some small issues and typos.
> Fixed some small mistakes on the commandline page.

- pt_BR/reference/mysqli/book.xml
> Update reference/mysqli/book pt_BR translation

- pt_BR/reference/math/functions/exp.xml
- pt_BR/reference/math/functions/octdec.xml
- pt_BR/reference/mysql/configure.xml
- pt_BR/reference/oci8/constants.xml
- pt_BR/reference/session/functions/session-id.xml
- pt_BR/reference/simplexml/simplexmlelement/getName.xml
- pt_BR/reference/var/functions/import-request-variables.xml
- pt_BR/security/globals.xml
Signed-off-by: Maurício Meneghini Fauth <mauriciofauth@gmail.com>
> Fix some errors

- pt_BR/reference/math/functions/rand.xml
Fix translation mispelling at /reference/math/functions/rand.xml
> Fix transation at reference/math/functions/rand.xml

- pt_BR/reference/classobj/functions/trait-exists.xml
Created translation of trait_exists function
> Created translation

- pt_BR/reference/classobj/functions/class-alias.xml
- pt_BR/reference/classobj/functions/get-called-class.xml
- pt_BR/reference/classobj/functions/get-declared-traits.xml
- pt_BR/reference/classobj/functions/trait-exists.xml
- Fixed credits with github, added @ 
- Added translation of the function class_alias
- Added translation of the get_called_class function
- Added translation of the get_declared_traits function
> Fixed credits with github, Added translation of the function class_alias

- pt_BR/reference/filter/filters.xml
Created all translation of the filters
> Translation filter

- pt_BR/appendices/migration71.xml
- pt_BR/appendices/migration73.xml
- pt_BR/appendices/migration74.xml
- pt_BR/appendices/migration71.xml
- pt_BR/appendices/migration73.xml
- pt_BR/appendices/migration74.xml
> Add PT-BR translations for some migration intros

- pt_BR/appendices/about.xml
- pt_BR/language/basic-syntax.xml
- pt_BR/language/constants.xml
- pt_BR/language/types/array.xml
- pt_BR/language/types/boolean.xml
- pt_BR/language/types/callable.xml
- pt_BR/language/types/float.xml
- pt_BR/language/types/integer.xml
- pt_BR/language/types/null.xml
- pt_BR/language/types/object.xml
- pt_BR/language/types/pseudo-types.xml
- pt_BR/language/types/resource.xml
Arquivos atualizados e corrigidos:
* pt_BR/appendices/about.xml
* pt_BR/language/types/array.xml
* pt_BR/language/basic-syntax.xml
* pt_BR/language/constants.xml
* pt_BR/language/types/boolean.xml
* pt_BR/language/types/callable.xml
* pt_BR/language/types/float.xml
* pt_BR/language/types/integer.xml
* pt_BR/language/types/null.xml
* pt_BR/language/types/object.xml
* pt_BR/language/types/pseudo-types.xml
* pt_BR/language/types/resource.xml
> Update many documents

- pt_BR/language/exceptions.xml
- pt_BR/language/expressions.xml
- pt_BR/language/functions.xml
- pt_BR/language/types/string.xml
- pt_BR/language/types/type-juggling.xml
Arqivos atualizados e corrigidos.
* pt_BR/language/types/type-juggling.xml
* pt_BR/language/types/string.xml
* pt_BR/language/exceptions.xml
* pt_BR/language/expressions.xml
* pt_BR/language/functions.xml
> A lot of updates

- pt_BR/appendices/migration53.xml
- pt_BR/reference/mysqli/ini.xml
doc: faz a tradução de pt_BR/reference/mysqli/ini.xml e corrige alguns erros de sync dele e de pt_BR/appendices/migration53.xml
> doc: faz a tradução de pt_BR/reference/mysqli/ini.xml e corrige
